### ISSUE TITLE
No such file or directory: 'globalAlignment_khush.backbone'

### ISSUE THREAD

**Issue by Logan1x** [jambler24/GenGraph#31]
Hey, I am trying to run example code in your repo(sequences.txt) with some modifications in local system but I am having this problem.

```
$ python3 ./gengraphTool.py make_genome_graph --seq_file sequences.txt --out_file_name khush --recreate_check
Running GenGraph Toolkit
Creating genome graph
[OrderedDict([('seq_name', 'H37Rv'), ('aln_name', 'seq0'), ('seq_path', '/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/TestGraphs/H37Rv.fa'), ('annotation_path', 'NA')]), OrderedDict([('seq_name', 'H37Rv1'), ('aln_name', 'seq1'), ('seq_path', '/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/TestGraphs/H37Rv1.fa'), ('annotation_path', 'Na')]), OrderedDict([('seq_name', 'H37Rv2'), ('aln_name', 'seq2'), ('seq_path', '/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/TestGraphs/H37Rv2.fa'), ('annotation_path', 'Na')])]
Conducting progressiveMauve
progressiveMauve Complete
Traceback (most recent call last):
  File "./gengraphTool.py", line 136, in <module>
    genome_aln_graph = bbone_to_initGraph(bbone_file, parsed_input_dict)
  File "/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/gengraph.py", line 1616, in bbone_to_initGraph
    backbone_lol = input_parser(bbone_file)
  File "/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/gengraph.py", line 1189, in input_parser
    in_file = open(file_path, 'r')
FileNotFoundError: [Errno 2] No such file or directory: 'globalAlignment_khush.backbone'
```

Can you please help me out?

Also, I have one more question to ask, Can I make De-Bruijn Directed graph using this library?

**Comment by Logan1x** [comment]
@jambler24 Can you help me out?

**Comment by minu7** [comment]
I had the same error and the problem was that i hadn't installed the progressiveMauve tool as indicated in Wiki.
Once you have installed progressiveMauve, it is useful to move the bin in you PATH (/bin for example) so you can call progressiveMauve from command line.
Everything is correct when you run progressiveMauve from command line and get response other than the command not found

**Comment by Logan1x** [comment]
> it is useful to move the bin in you PATH 

Can you help me with this, I am using Linux. I just downloaded the zip, which has Mauve.

**Comment by minu7** [comment]
In the zip you should have the progressiveMauve and you need to copy it to / bin

**Comment by jambler24** [comment]
Hey, thanks for the input @minu7 !

If it is a problem with mauve not being in your path, you can also specify where it is with:

--progressiveMauve_path /path/to/progressiveMauve

Otherwise:

https://unix.stackexchange.com/questions/26047/how-to-correctly-add-a-path-to-path

**Comment by jambler24** [comment]
Will make a note for a better error message. Please let us know here if that solved the problem.

**Comment by Logan1x** [comment]
so I did ran by giving external path with progressiveMauve_path flag but It seems to get another error,

```
$ python ./gengraphTool.py make_genome_graph --seq_file sequences.txt --out_file_name khush --recreate_check --progressiveMauve_path /home/noob/Downloads/mauve_snapshot_2015-02-13/linux-x64/progressiveMauve
Running GenGraph Toolkit
Creating genome graph
[OrderedDict([('seq_name', 'H37Rv'), ('aln_name', 'seq0'), ('seq_path', '/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/TestGraphs/H37Rv.fa'), ('annotation_path', 'NA')]), OrderedDict([('seq_name', 'H37Rv1'), ('aln_name', 'seq1'), ('seq_path', '/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/TestGraphs/H37Rv1.fa'), ('annotation_path', 'Na')]), OrderedDict([('seq_name', 'H37Rv2'), ('aln_name', 'seq2'), ('seq_path', '/home/noob/Documents/IIITD/tavlab/strainflow/GenGraph-master/TestGraphs/H37Rv2.fa'), ('annotation_path', 'Na')])]
Conducting progressiveMauve
Error: progressiveMauve_call output appears empty.

```

**Comment by minu7** [comment]
Try to pull the latest library update and try again

**Comment by Logan1x** [comment]
Thanks I'll try that.

**Comment by 8banzhuan** [comment]
Hey，I use windows，I had installed progressiveMauve，Next, how can I use it in pycharm under windows system, thank you
